.gitignore, Client/WarFare/UILogin.cpp, Server/GameServer/User.cpp
Server doesn't allow user to send unhandled packets in Release mode,
since the Client sends WIZ_TIMENOTIFY packet periodically, we have to
allow it in Server side.
=> WIZ_TIMENOTIFY disconnect in Release mode.

Client/WarFare/GameProcMain.cpp, Client/WarFare/GameProcedure.cpp, Client/WarFare/GameProcedure.h, Client/WarFare/LocalInput.cpp
Added a bool to check if the game window has mouse focus from an SDL event.  I also put conditional around the rotation of the camera in the case that a user moves to the edge of the screen with their mouse. Now the character will no longer rotate camera if they leave the game window with their mouse.
=> Camera now only turns if window has mouse focus.

.gitignore, Client/WarFare/GameDef.h, Client/WarFare/GameProcMain.cpp, Client/WarFare/PacketDef.h, Server/shared/packets.h
Updated the fx, ui_us, and zone structure to match the new tbl files from v1.298. I've also added all definitions from the ui_us.tbl into GameDef.h. 
I've also made a small stub out of implementing subopcode 6 for NoviceClassChange. I will implement a small function in the GameProcMain client side as described in the ase N3_SP_NOVICE_CLASS_CHANGE_REQ:
=> GameDef.h ReStructure for 1298 & Stub out for NoviceClassChange

Client/WarFare/UIStateBar.cpp, Client/WarFare/UIStateBar.h
- implemented the zoom buttons
- added minimap-clamping (no info outside the map, no looking outside the map)
- added basic code for future handling of the QuestHelper/PowerupStore-Buttons
- cleaned up the blinking code for expiring magic
Zoomlevels and steps can be kept as is or modified to match the official values if someone finds out.
Could not check as minimap-zooming is broken/not implemented in the binary client either.
=> implements minimap-zoom, cleaned up blinking magic, adds Quest/PUS-buttons

Client/WarFare/GameProcMain.cpp
Simply clears out the old values of the string array for each time command is executed so it won't re-send the same values.
=> Resolves issue #102

Client/WarFare/UISkillTreeDlg.cpp, Client/WarFare/UISkillTreeDlg.h
About Skill Icons which are not available
In skill tree dialog, there are no icons for skills which not available on our level
I try to implement it, also i create new function for checking the skill if its available on our current level, when fires right click on icon (for put it hot key dialog).
I dont know this is the right and easiest way.
=> Skill icons which not available

Client/WarFare/UISkillTreeDlg.cpp
Using skill points to assasin on rogue and passion on warrior
=> Error on using skill points to assasin on rogue and passion on warrior.

Client/WarFare/UILogin.h, Client/WarFare/UIVarious.h
Remove deprecated std::binary_function and minor cleanup in __FriendsInfo and __GameServerInfo structs
* Resolves compilation error with VS2022 toolset (v143) due to removal of std::binary_function
=> Remove deprecated std::binary_function and minor cleanup in __FriendsInfo and __GameServerInfo structs

Server/GameServer/DBAgent.cpp
issue : cannot login same account after logging out the game because DB call does not work as intended. sp_help checking table in database shows it expects 4 parameters instead of 3. This commit aiming the solve the problem, now logged out accounts can login back without closing and reopening server.
=> Account logout fix

Client/WarFare/UIHotKeyDlg.cpp
Probably for testing purposes some part of the code is commented out and that causes drag / drop feature to not work from skilltree to hotkey. Re adding those solved the presenting issue.
=> fix for skill drag drop from skill tree to hotkey bar

Client/WarFare/GameProcMain.cpp, Client/WarFare/GameProcMain.h, Client/WarFare/resource.h, Server/GameServer/CharacterMovementHandler.cpp, Server/GameServer/User.h, Server/shared/packets.h
packet WIZ_WARP_LIST was causing game crash when an user tries to enter a zone ( Eslant ) without satisfying level requirement (40 or 60 in this version, tbl says 40 ). Packet did not read in correct order and warning message to user not shown. 
This commit aims to fix game crash problem when user tries to enter Eslant with low level character.
=> Wiz warp list fix game crash

Client/N3Base/N3FXPartParticles.cpp
This fixes the gathering point of particles like the 1920 heal, it should collect towards the upper character instead of dissapearing into the ground.
m_dwEmitType == FX_PART_PARTICLE_EMIT_TYPE_GATHER
m_uEmitCon.vGatherPoint = pSrc->m_uEmitCon.vGatherPoint;
=> vGatherPoint fix

Client/WarFare/GameDef.h, Client/WarFare/MagicSkillMng.cpp, Client/WarFare/MagicSkillMng.h
We have implemented a rotating loop for the mage and priest skills that target an area, the groundboard is in the centre rotating and the zonepointers are out the outer layer rotating clockwise it also scales by reading skilltbl3->iRadius and same for type4->iRadius
=> FXZonePointer fix

Client/WarFare/MagicSkillMng.cpp, Client/WarFare/MagicSkillMng.h
Simply put it works, I haven't tested potions items only mage skills but in theory they should work.
Not sure what to do with legacy code as it confuses me but this is better than what we have.
It does the job the only issue I came across is you cant Z (select nearest enemy) or select a monster with your mouse for 1-2 seconds after casting ends not sure if its related  to the packets we are sending the same .cpp or elsewhere like gameproc.
Addresses the following PR/issue: https://github.com/srmeier/KnightOnline/pull/163
=> Skill recast map fix

Client/WarFare/GameDef.h
this fix issue #188 
thankfully no need to change any tbl files or database
it was just the length of array MAX_ITEM_EXTENSION causing the problem.
Item_Ext tbls start with 0 and includes also 23 so array lenght must be 24, probably forgotten or changed to test something. 
All blue chest items like hanguk sword, hell breaker, enion bow visible with this update.
=> fix for item ext 23, blue chest items

Client/WarFare/MagicSkillMng.cpp
Skill mana requirement scales with attack for classes warrior and rogue.
Skill mana requirement now don't scale with attack.
This needs to be changed because at higher attack points ( if player is higher level and have better weapons ) this causes skills to be not casted. For example, a warrior with 500 AP cannot cast sword dancing, or cast it for high amount of mana. Normally it should be fixed to constant value which is 300 for sword dancing.
this is related to issue #201
=> required mana for skill should not scale with attack power

Client/WarFare/UIInn.cpp
Currently, if an user has clan, create clan feature does not show the message "you cannot create a clan because you have one"
It shows empty message because related line removed.
Now, it shows related error messages.
UIInn - Message function is edited, because not formated texts are forgotten there.
=> fix for missing clan error texts

Client/WarFare/MagicSkillMng.cpp, Client/WarFare/MagicSkillMng.h, Client/WarFare/N3UIWndBase.h, Client/WarFare/UIHotKeyDlg.cpp, Client/WarFare/UIHotKeyDlg.h
No cooldown visual displayed on top of skills/items in hotkey bar
Cooldown now renders for skills/items
Fix for issue #43 
-Added rendering logic in UIHotKeyDlg.
- UIHotKeyDlg will check the cooldowns in MagicSkillManager maps and render the cd for the current skillbar.
=> Hotkeys now display cooldown timer over them when used.

Client/WarFare/UIQuestTalk.cpp, Client/WarFare/UIQuestTalk.h
Current state : user cannot close NpcTalk menu with close button because close button visibility set as false inside UIQuestTalk.cpp, also it is not initialized and does not define as member.
m_pBtnClose initialized in constructor, defined in header file and its visibility set as default ( visible ). By this way, button is visible now and user can close NpcTalk menu by clicking the button.
This change improves user experience, close button should be working, otherwise user is forced to display all of the messages of selected npc.
=> fix user cannot close npctalk menu with close button

Client/WarFare/GameProcMain.cpp, Client/WarFare/UIPartyBBS.cpp
Max level of seeking party text has been set as 60.
It has been set as 80 which is the actual max level for 1299 version.
This was causing misinformation for high level characters for example if a 79 level user opens seeking party feature, he/she sees level range as 71-60 and that is wrong.
=> max level limit in seeking party text changed to 80

Client/N3Base/N3UIBase.cpp, Client/WarFare/UISkillTreeDlg.cpp, Client/WarFare/UISkillTreeDlg.h
current class names on skill tree for el morad is not visible properly because kasar hood ( master rogue ) text is not closed correctly. Hence, for a warrior without master, class name seen as kasar hood, although it should be Blade.
Now, it is seen as Blade as it should be.
ID written wrong in func SetPageInCharRegion(), in SkillTreeDlg.cpp.
=> kasar hood ID written wrong, causes it not to be closed

UIE/PropertyView.cpp, UIE/UIEDoc.cpp
project is set multibyte at start (although it is not stated in project file). CString to std::string conversion is not done and so project does not compile.
Project compiles and opens.
=> cstring conversion to compile uie

.github/workflows/build.yml, .github/workflows/build_tools.yml, Client/N3Base/N3Base.vcxproj
* Add build.yml for basic client & server build (manually, on PR to master & on push to master)
* Add build_tools.yml for the various tools (manually, and weekly every Sunday at midnight)
The client & server build is already time consuming at ~3min+, so we'll keep the tool builds (which don't currently all build anyway) separate.
It may not necessarily be worth keeping the server build either, since most of the changes will rely on the client.
We may want to use labels as triggers to denote which actually needs building, although when multiple do, doing it this way will cause it to use the maximum amount of time rather than sharing the existing libs.
See #229
=> Add build workflows

Client/WarFare/GameProcMain.cpp
weight info sent as uint16_t from server but read as int16_t at client. Therefore, overflow happens when the user have higher numbers than 3276,7 ( 32767 int16_t max) . 
static cast to int after reading as uint16_t so it does not overflow anymore.
For a high level character with maxed STR, game is unplayable. Because of this bug, user cannot buy / trade items.
=> weight bug fix

Client/WarFare/GameBase.cpp, Client/WarFare/GameBase.h, Client/WarFare/UIInventory.cpp
format number works inside UIInventory, however other UI components need similar function to format gold such as : UITransactions, UIWarehouse etc.
FormatNumber function is carried under GameBase and can be accessed from other UI elements. In addition, future update to change separator from "," to "." can be performed with respect to language tail.
to decrease amount of code repeat.
=> replace formatnumber function inside gamebase

Client/WarFare/GameProcMain.cpp, Server/Ebenezer/StdAfx.h, Server/Ebenezer/User.cpp, Server/Ebenezer/User.h
weight works fine in compiled client but it does not work on binary client. Hence, instead of static casting int, weight limit set as INT16_MAX. Probably, officially it was in that way.
Max weight set as INT16_MAX on server side works in both clients.
Old fix was not working on original exe.
=> better solution to weight bug, which works in both clients

Client/WarFare/GameProcMain.cpp, Client/WarFare/UITransactionDlg.cpp, Client/WarFare/UITransactionDlg.h, Client/WarFare/UIVarious.cpp
weight text is not used although it presents on uif file. User cannot see weight change on the state of trading with NPC.
weight is updated after trade, and text is visible on ui.
it was missing core feature
=> weight text update while trading with NPC

Client/WarFare/UILogin_1298.cpp, Client/WarFare/UILogin_1298.h
* Move server selection logic into a separate method to be invoked on-demand.
* Rather than reset everything to white on any string selection, require a list entry to actually be selected.
* Also allow for any selected server to be connected to when pressing enter.
Currently, we have 2 main issues:
1. Any string click triggers all server list entries to effectively become visually unselected.
2. For some reason, the behaviour for 'enter' merely selects the first server if one's not already selected.
1. String clicks no longer inherently visually reset the list. Only string clicks on valid list entries do, because they also mark their corresponding selected entry as such.
2. Enter will now just trigger a connect on the selected server. As …
=> CUILogIn_1298: Fix various server list logic

Client/WarFare/UIManager.cpp
Its logic to close mutually exclusive UIs was commented out in the base source. This should be restored, as they did officially.
UIs that use the styles UISTYLE_POS_LEFT, UISTYLE_POS_RIGHT or UISTYLE_SHOW_ME_ALONE are not currently closed when UIs they are mutually exclusive with are opened.
These such UIs will now be correctly closed, so they aren't all up at the same time.
This logic was commented out in the original leaked source, and later restored as evident in the official binary.
We should also restore it here, so that we don't have to implement visibility updating logic for these UIs manually.
=> Restore CUIManager::SetVisibleFocusedUI() logic

Client/N3Base/My_3DStruct.h, Client/N3Base/N3PMeshCreate.cpp, Client/N3Base/N3Shape.cpp, Client/N3Base/N3ShapeExtra.cpp, Client/N3Base/N3Terrain.cpp, Client/WarFare/GameProcMain.cpp, Client/WarFare/PlayerBase.cpp, Client/WarFare/PlayerOtherMgr.cpp, Client/WarFare/PlayerOtherMgr.h, Client/WarFare/UIMessageBoxManager.cpp, N3ME/LyTerrain.cpp, N3ME/MapMng.cpp, N3ME/QTNode.cpp, N3ME/StdAfx.h, TblEditor/framework.h
Fairly explanatory; bunch of useless template helpers, mostly unused. T_Min() and T_Max() were implemented incorrectly (but assumed to be correct), T_Abs() was occasionally used, T_Delete() was used but only in conjunction with removing or replacing the pointer, so it initialising it to nullptr after-the-fact was pointless.
T_Min(), T_Max(), T_Abs() were all replaced with their std variants (std::min(), std::max(), std::abs()).
T_Delete() was just replaced with `delete`.
Everything else was just removed outright since there was nothing using them.
=> Strip the useless template helpers

Client/N3Base/N3Eng.cpp, Client/N3Base/N3Eng.h
In DX8 this automatically blocked until this happened, in DX9 this has to be done manually.
This is roughly the official implementation for this, give or take the log messages using %X (hex) for the error codes (more meaningful for these error codes) rather than %d.
=> Wait for DX9 device to be restored

ItemEditor/base.cpp
These should be delete[], as they were allocated with new[].
Also a singular delete which should've been delete[].
=> ItemEditor: Fix some mismatched free calls

Server/AIServer/GameSocket.cpp, Server/AIServer/ServerDlg.cpp, Server/Ebenezer/AISocket.cpp, Server/Ebenezer/EbenezerDlg.cpp
AG_COMPRESSED_DATA checksums should be of the decompressed data.
Additionally, we should throw assertions for these cases rather than simply silently ignoring them.
=> AG_COMPRESSED_DATA checksums should be of the decompressed data

Client/WarFare/GameDef.h, Client/WarFare/GameProcLogIn_1098.cpp, Client/WarFare/GameProcLogIn_1298.cpp
Since a default isn't otherwise provided with the assets, I think defaulting this in debug builds is a fair compromise.
We should probably just create a default when it's pulled, but for now this helps things to "just run".
There's no reason to keep this behaviour in release builds since it's only intended for local development.
They can setup server.ini if they need to.
=> Default login server IP to 127.0.0.1 in debug builds

.github/workflows/build_all.yml, .github/workflows/build_client.yml, .github/workflows/build_client_tools.yml, .github/workflows/build_server.yml, .github/workflows/build_tools.yml
Go back to triggering build_all.yml for everything. Only trigger the others if we explicitly change those workflows (or if we manually request it).
Additionally, in "all", rather than just running All.sln (and having no idea how many are actually left), we run each of the individual solutions to break up the workflow's progress in a measurable way.
=> Simplify workflows

Client/N3Base/N3SkyMng.cpp, Client/N3Base/N3VMesh.cpp, Client/WarFare/GameProcMain.cpp, Client/WarFare/GameProcMain.h, Client/WarFare/PlayerBase.cpp, Client/WarFare/PlayerBase.h, Client/WarFare/PlayerMySelf.cpp, Client/WarFare/PlayerMySelf.h
A few issues with auto-attack:
Doesn't work most of the time with R. Not as bad with double-click but still not great
Pressing R won't cause the player to run up to the target if out of range
This all works well on the goatcheez client, so it is a client problem.
Auto-attack behaves as it does on the goatcheez client. R and double click function the same way.
Auto-attack was a broken mess.  You had to be on top of the monster and double click for a chance to get an auto attack to proc.  Makes basic testing a hassle.
=> #323 Fix auto-attack

Client/N3Base/N3UIBase.cpp, Client/N3Base/N3UIBase.h, Client/N3Base/N3UITooltip.cpp, Client/N3Base/N3UITooltip.h, Client/WarFare/N3UIWndBase.cpp, Client/WarFare/UICharacterSelect.cpp, Client/WarFare/UIDead.cpp, UIE/PropertyView.cpp
Each control needs to store its own individual tooltip colour to be used when invoking a tooltip from that control.
As such, each place the tooltip needs to be invoked, we now pass its colour along as well to CN3UITooltip to modify the colour of the text.
Resolves #318
=> Store and pass control tooltip colour to CN3UITooltip

Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/EbenezerDlg.h, Server/Ebenezer/User.cpp, Server/Ebenezer/User.h
For now this is just /town (WIZ_HOME / CUser::Home()). Officially it'd extend to respawning, warping, etc too.
It should also handle things like CSW overrides, but we don't implement this yet.
Resolves #319
Since START_POSITION isn't loaded, the server only uses HOME for /town.
This is exclusively used during war invasions, so the /town coordinates are wrong for the only zones it supports (1 & 2).
Since other zones don't exist in it, naturally /town doesn't behave either.
We load up START_POSITION (again). For /town specifically (though more should be added, like respawning), we now use it to fetch the appropriate /town coordinates per nation.
=> Implement START_POSITION for /TOWN

props/nanodbc.props
For simplicity, when fetching, we should just initialize to defaults if a column is NULL, rather than throwing.
This way we don't have to strictly keep our database synced with user databases (at least, for this purpose).
=> Add custom NANODBC_DISABLE_NULL_ACCESS_ERROR

Server/AIServer/Npc.cpp, Server/AIServer/ServerDlg.cpp, Server/AIServer/ServerDlg.h, Server/AIServer/User.cpp, Server/Aujard/AujardDlg.cpp, Server/Aujard/AujardDlg.h, Server/Ebenezer/AISocket.cpp, Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/EbenezerDlg.h, Server/Ebenezer/MagicProcess.cpp, Server/VersionManager/VersionManagerDlg.cpp, Server/VersionManager/VersionManagerDlg.h, Server/shared/logger.cpp, Server/shared/logger.h
Very loosely wrap spdlog log runners for better RAII encapsulation, also allowing us to move consumer logic out of the shared library.
Additionally, make sure we're only appending the base directory to relative paths.
=> Wrap spdlog runner

Client/WarFare/WarFare.vcxproj, Client/WarFare/WarFare.vcxproj.user.default
We don't need a user default for this at all.
Note that it will no longer show in the IDE, but this only matters if you're changing it anyway.
=> Move debugger defaults to the project file

Client/N3Base/N3SndMgr.cpp
The prediction was off, but it's just wasted memory regardless. The original intent was to reuse this logic for loading the mmio buffer from memory, but after looking more at the interfaces, I never bothered to go down that route; it wasn't worth it.
So we'll conserve memory and avoid unintentional overruns here from bad prediction code by just writing back out in chunks.
Closes #372
=> Chunk MP3 decoder writes instead of predicting and writing in one go

build_scripts/build_dependency.cmd, build_scripts/clean_dependency.cmd
`clean_dependency.cmd` currently assumes we're cleaning a dependency with a build project.
As this logic is shared and invoked by everything, rather than handled on a case-by-case basis since we need it to reset the "last build state" (or fetch state in this case), we need to simply let it continue to handle and clean the "last build state" even for projects that don't actually have a project to build (e.g. ko-client-assets, dx9sdk).
=> Allow for cleaning fetch-only submodules

Client/WarFare/PlayerMySelf.cpp
clan font is not bold
clan font is set as bold on CPlayerMyself class
used predefined flag inside CFont class ( D3DFONT_BOLD ). It was inside SetText function before, but it seems it should be used while creating object.
=> fixing clan font for playermyself

Client/WarFare/GameDef.h, Client/WarFare/UIInventory.cpp, Client/WarFare/UIInventory.h
number of scrolls not seen correct on inventory and hotkey UIs.
They seen correct.
Scroll quantity is controlled by iDurability instead of iCount
=> Display scroll charges ("durability") on UIs

Client/WarFare/GameProcMain.cpp, Server/Ebenezer/User.cpp
features related to WIZ_STATE_CHANGE packet does not work
they work now
return type of server should be converted to uint32_t instead of byte, this is probably done to support official also.
=> Promote WIZ_STATE_CHANGE buff type to 32-bit

Server/AIServer/GameSocket.cpp, Server/AIServer/MagicProcess.cpp, Server/AIServer/Npc.cpp, Server/AIServer/NpcMagicProcess.cpp, Server/AIServer/NpcThread.cpp, Server/AIServer/Party.cpp, Server/AIServer/RoomEvent.cpp, Server/AIServer/ServerDlg.cpp, Server/AIServer/ServerDlg.h, Server/AIServer/User.cpp, Server/Ebenezer/AISocket.cpp, Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/EbenezerDlg.h, Server/Ebenezer/KnightsManager.cpp, Server/Ebenezer/MagicProcess.cpp, Server/Ebenezer/Npc.cpp, Server/Ebenezer/UdpSocket.cpp, Server/Ebenezer/User.cpp
It's a little verbose, but we no longer use 'Array' to denote maps (we use 'Map' instead, and only continue to use 'Array' for vectors since it's the same basic concept), but we always explicitly indicate whether it's a table container or not via 'Table'.
This is because of cases like the NPC map; there's an NPC table (i.e. the NPC table map) and then there's the regular NPC (instance) map.
=> Rename server table and related maps/containers for consistency

Client/WarFare/UISkillTreeDlg.cpp
The code committed to https://github.com/Open-KO/KnightOnline/pull/311 during my clean up was not the correct one due to commits being wrong
Fixes a bug introduced in my code clean up where the bottom row (m_pStr_skill_item2) was not displayed
Render m_pStr_skill_item2 to show the bottom line of the hover-over skill tips.
Line is highlighted in yellow on demo below.
=> UITreeSkillDlg - Update to tooltip on skill hover - show skill_item2 

Client/WarFare/GameDef.h, Client/WarFare/GameProcMain.cpp, Client/WarFare/PacketDef.h, Client/WarFare/PlayerBase.h, Client/WarFare/UIPartyOrForce.cpp, Client/WarFare/UIPartyOrForce.h
The Party UI is bugged #46 
The party UI only displayed the information for the party members and MP bars are operating.
Future work needed to align with official for party UI:
- Check the curses, slows, DOTs etc are working as per official client
- Change party user names to yellow
- Provide party icon to leader
- Make user names in party UI have a black outline
- Possible others but have not tested every part, just started on this.
1. The UIF data was not referenced correctly.
2. Hide/ show of the data was not configured correctly
3. Linked up the MP part of the packet for N3_SP_PARTY_OR_FORCE_HP_CHANGE
4. Changed some typos in the comments that referred to the wrong codes
Screen shot of working party UI
=> PartyUI - HP Bars, MP Bars and Names

Server/Ebenezer/User.cpp
cannot login game if level is 80
can login now.
important for testing 80 level skills.
=> Allow level 80 characters to login

Client/WarFare/UICharacterSelect.cpp, Client/WarFare/UICharacterSelect.h
The back button on the character selection screen is currently explicitly hidden.
This is moved into position as matching the UIF (15 pixels above the "Exit" button).
Server/client logic does not handle this exceptionally well, but since arbitrary unrelated fresh connections to a freshly restarted server with an empty CURRENTUSER table seems to be flakey all on its own, that's a problem for another time. There's likely a few different unrelated issues at play there.
*When* a connection is correctly established, it does tend to allow you to go back now, and then reconnect to the game server just fine.
Resolves #44
=> Restore back button for character selection

Client/WarFare/GameProcMain.cpp, Server/shared/ByteBuffer.h
Stream operators are nice, but particularly for reads, they mask problems here. If a type externally changes, there's no way to enforce or make it immediately clear what type we're reading.
We should just be explicit about it so that the protocol is immediately obvious and consistent.
Writing is another story. I leave the `>>` operators for now; it may be worth replacing them, but this issue is mitigated simply by enforcing the cast when using the operator, e.g.:
```cpp
pkt << uint16_t(field);
```
This makes it immediately obvious what the protocol is and avoids it breaking when `field` changes externally, though code-wise it obviously isn't enforced. It also ends up not obviously pairing with the reads, but I think it's still a step in the right direction for enforcing consistent …
=> ByteBuffer: Force explicit reads via read<T>()

Client/WarFare/GameDef.h, Client/WarFare/GameProcLogIn_1098.cpp, Client/WarFare/GameProcLogIn_1098.h, Client/WarFare/GameProcLogIn_1298.cpp, Client/WarFare/GameProcLogIn_1298.h, Client/WarFare/GameProcedure.cpp, Client/WarFare/GameProcedure.h, Client/WarFare/WarFareMain.cpp
As-is, the client can spam successful game server connections as there's a window between it connecting and sending the WIZ_VERSION_CHECK packet, and it getting a response. In this window, the player can initiate another request, causing it to establish another connection. If the WIZ_VERSION_CHECK packet from the first connection is received, it ends up associating the wrong encryption key -- because that's no longer the session it's using it for.
Notably this is, for the most part, official behaviour. It is very possible to continue to spam the game server with the official client, but they force a 1s delay between connection requests which limits the frequency you can actually spam. The bug is still very much an issue there though.
The official Sleep() approach isn't ideal; it doesn't …
=> Add unofficial internal cooldown to establishing game connections

Client/WarFare/UIExitMenu.cpp
uses old way to load UI elements.
__ASSERT is replaced with N3_VERIFY_UI_COMPONENT
code clean-up.
=> CUIExitMenu: Use N3_VERIFY_UI_COMPONENT

Client/WarFare/UIHelp.cpp, Client/WarFare/UIHelp.h
load use old way, NULL macro is used.
NULL changed to nullptr
N3_VERIFY_UI_COMPONENT used to load UI elements 
Button type changed to N3UIButton from N3UIBase
CN3UIButton included on header
clean up & to provide match other parts of UI.
=> CUIHelp: Use N3_VERIFY_UI_COMPONENT + CN3UIButton button types

Client/WarFare/ClientResourceFormatter.h
Buggy code tends to rely on this for existence checks (which it shouldn't need to do). It should be updated, but we'll revert behaviour here for consistency for now.
Resolves #451
=> fmt::format_text_resource(): Simply return an empty string always

Server/Ebenezer/AISocket.cpp, Server/Ebenezer/User.cpp
Consistently prevent using the enemy faction's warp gates.
Also ensure WIZ_OBJECT_EVENT still errors with the object type, and suppress warnings related to the object types being passed in the packets.
Resolves #343
=> Consistently prevent using the enemy faction's warp gates

Client/N3Base/My_3DStruct.h, Client/N3Base/N3FXPartBase.h, Client/N3Base/N3FXPartBillBoard.h, Client/N3Base/N3FXPartBottomBoard.h, Client/N3Base/N3FXPartMesh.h, Client/N3Base/N3FXPartParticles.h, Client/WarFare/BirdMng.cpp, Client/WarFare/UIClassChange.cpp, Client/WarFare/UIClassChange.h, Client/WarFare/UIHelp.h, Client/WarFare/UINPCChangeEvent.cpp, Client/WarFare/UINPCChangeEvent.h, Client/WarFare/UIPartyBBS.cpp, Client/WarFare/UISkillTreeDlg.cpp, Client/WarFare/UIStateBar.cpp
Restore `_ASSERT()` assertion & debug output behaviour.
Only enable in debug builds.
Update or otherwise disable control loads for UIs/misc. other affected things which were previously throwing assertions.
Resolves #442
=> Restore _ASSERT behaviour

Client/WarFare/UIVarious.cpp, Client/WarFare/UIVarious.h
The clan UI currently displays the number of users who will be rendered in the list of members. This is different between a clan leader (who gets a full list) and members (who gets an online list).
The new behaviour displays the number of members online and the number of total clan members.
To align with the official client behaviour. Checked the packet and the parts that were identified as unused contained the missing data needed to correctly populate the UI.
=> CUIKnights: Display member counts

Client/WarFare/UICharacterCreate.cpp, Client/WarFare/UICharacterCreate.h
Despite being named img\_\*, these controls are actually strings.
Fixed their type, and renamed the member var to be a little more explicit.
This fixes an assertion caused by it not finding the correct type.
=> CUICharacterCreate: Fix stat label type (image -> string)

.gitignore, Server/AIServer/ServerDlg.cpp, Server/AIServer/stdafx.h, Server/Aujard/DBAgent.cpp, Server/Aujard/StdAfx.h, Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/StdAfx.h, Server/ItemManager/StdAfx.h, Server/VersionManager/stdafx.h, Server/shared/server_config.h.default, Server/shared/shared.vcxproj, Server/shared/shared.vcxproj.filters
This allows for databases where the names are padded (due to being stored in CHAR(N) columns instead of VARCHAR(N)). Our existing database has a few such cases, combined with some data remnants from when a column was padded but is no longer.
This will be entirely replaced in future, but for now we'll just allow for such cases.
For future reference, an exhaustive list of all unnecessarily padded columns and fields in procedures:
BATTLE
COPY_SERIAL_ITEM
FRIEND_LIST
HACKTOOL_USERLOG
HERO_USER
ITEM (data only)
ITEM_UPGRADE
KNIGHTS_RATING
RENTAL_ITEM
RENTAL_ITEM_LIST
TERM_ITEM
USER_EDITOR
USER_EDITOR_TERM
USER_KNIGHTS_RANK
USER_PERSONAL_RANK
USER_RENTAL_ITEM
USER_SAVED_MAGIC
USERDATA_SKILLSHORTCUT
WAREHOUSE
WEB_ITEMMALL
WEB_ITEMMALL_LOG
CHANGE_CASTLE_COMMERCE
CREATE_KNIGHTS
CREATE_KNIGHTS2 …
=> Add DB_COMPAT_PADDED_NAMES

Server/AIServer/ServerDlg.cpp, Server/AIServer/ServerDlg.h, Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/EbenezerDlg.h, Server/VersionManager/VersionManagerDlg.cpp, Server/VersionManager/VersionManagerDlg.h
The servers will now report the main port they're listening on and when it allows connections (it can listen, but block until connections are allowed).
Additionally, regarding AI, we report and log the IP:port we're connecting to.
Removed the awkward ResetOutputList() behaviour so we can log appropriately. This will all be changed with a console at some point, so this really doesn't make sense to keep anyway.
Resolves #482
=> More informative server connection behaviour

Client/N3Base/N3Eng.cpp
Fixes an official lighting bug still present in the official 1.298 client where the device doesn't reset lighting states on device loss.
=> Restore lighting on device loss

Client/WarFare/GameProcMain.cpp
We should reset these so old states from, for example, CGameProcCharacterSelect, don't contaminate.
CGameProcMain will setup its own light states.
This fixes a bug on some drivers (VMWare's, at least) where these previously enabled light states somehow completely break lighting where they don't on typical drivers:
=> Reset lighting entering the CGameProcMain scene

Client/N3Base/N3Base.h, Client/N3Base/N3SndMgr.cpp, Client/WarFare/WarFareMain.cpp
It's not technically implemented like official, but it's close enough based on our current implementation.
Officially (in 1.298) it's implemented so the setting applies on-demand, technically allowing for it to be changed live. You can't actually change it live though, so effectively it doesn't really matter that we're just preemptively blocking it from loading sounds.
Resolves #490
=> Update sound config to globally disable/enable as per official

Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/EbenezerDlg.h
We default this to 1 for simplicity, even though officially it's defaulted to 0 and fails when not set (i.e. 0).
This is so that it's easy to just load up the official server after running this server once, as this default will be written back to file.
=> Ebenezer: Load server index from config

N3ME/DTex.cpp, N3ME/DTexGroupMng.cpp, N3ME/DTexMng.cpp, N3ME/MainFrm.cpp, N3ME/MapMng.cpp
Shutdown shouldn't be invoking Release() here, in some cases twice. Release() tends to reset, which can involve UI operations which may not be valid at this point.
We should just explicitly free instead.
=> N3ME: Fix shutdown behaviour

Client/N3Base/N3Chr.cpp
CN3Chr::Min() and CN3Chr::Max() apply CN3Chr::m_Matrix, only for us to effectively attempt to remove it via finding its inverse and applying that.
We can just throw those away entirely and use m_vMin and m_vMax directly.
It was probably only like this because it was handled externally and they didn't have access to them directly.
=> CN3Chr::RegenerateCollisionMesh(): Remove redundant transformations

Server/Ebenezer/EbenezerDlg.cpp, Server/Ebenezer/EbenezerDlg.h, Server/Ebenezer/GameDefine.h, Server/Ebenezer/KnightsSiegeWar.cpp, Server/Ebenezer/KnightsSiegeWar.h, Server/Ebenezer/LOGIC_ELSE.cpp, Server/Ebenezer/User.cpp, Server/Ebenezer/User.h
We implement  (exposing unused server members for them):
* CHECK_MONSTER_CHALLENGE_TIME
* CHECK_ITEMCHANGE_NUM
* CHECK_MIDDLE_STATUE_NOCAPTURE
* CHECK_MIDDLE_STATUE_CAPTURE
* CHECK_NO_CASTLE (loading KNIGHTS_SIEGE_WARFARE for this info)
* CHECK_CASTLE (loading KNIGHTS_SIEGE_WARFARE for this info)
* CHECK_MONSTER_CHALLENGE_USERCOUNT
* CHECK_BEEF_ROAST_KARUS_VICTORY
* CHECK_BEEF_ROAST_ELMORAD_VICTORY
* CHECK_BEEF_ROAST_NO_VICTORY
Refs #260
=> Implement more EVT opcodes
