- Client/WarFare/GameBase.cpp
- Client/WarFare/GameProcMain.cpp
- Client/WarFare/MagicSkillMng.cpp
- Client/WarFare/PlayerMySelf.cpp
- Client/WarFare/UICmd.cpp
The actual source was lack of the complete 33 tips which being used in
1.298 (IDS_HELP_TIP_ALL)
* Last Pull Request was wrong , although this one is the one!
>  Added 1.298 Tips for Client source

- Client/WarFare/GameProcMain.cpp
> Added Notification of money lost/earned/spend

- Client/N3Base/N3Base.h
- Client/WarFare/GameProcedure.cpp
- Client/WarFare/WarFareMain.cpp
- Server/AIServer/ServerDlg.cpp
- Server/GameServer/GameServerDlg.cpp
- Server/LogInServer/LoginServer.cpp
- Server/shared/Ini.cpp
(As I have also written this in the description of the first commit)Unfortunately, I'm working with VS2017 community with on windows 10, so I had to upgrade the solution to v141, so to be sure, please make sure the code is still compatible with VS2015 before merging.
> GetPrivateProfileInt dependency is removed and the default values of some hardcoded strings are changed

- Server/GameServer/GameServerDlg.cpp
- Server/GameServer/NPCHandler.cpp
Apparently the reason why the client doesn't show the coin lost/gained due to  the fact that server doesn't inform the client correctly.
> Server, now, notifies the player when they buy/sell item from/to npc

- Client/N3Base/N3UIString.cpp
- Client/N3Base/N3UIString.h
- Client/WarFare/UIImageTooltipDlg.cpp
fixed approximation function in N3UIString, and added a function to measure the actual dimensions.
cleaned up the tooltip-building and fixed the OOB-check with the cursor-offset.
> fix tooltip size by measuring strings

- Client/WarFare/WarMessage.cpp
Fixes a problem with the scroller getting stuck on high-fps. Also added full outlines (instead of top-left and bottom-right only).
> fixes notice-scroller movement and outlines

- Client/WarFare/GameProcLogIn.cpp
- Client/WarFare/GameProcLogIn.h
- Client/WarFare/UILogin.cpp
- Client/WarFare/UILogin.h
Implemented the Registration-button on the Loginscreen by reading the website-address from the Server.ini (as the 1299 binary client does) and opening it using shellexecute.
> Implement Registration/Homepage-Button on Loginscreen

- Client/WarFare/GameProcMain.cpp
- Client/WarFare/GameProcMain.h
- Client/WarFare/GameProcedure.cpp
- Client/WarFare/GameProcedure.h
- Client/WarFare/UIChat.cpp
- Client/WarFare/UIChat.h
- Client/WarFare/UIMessageWnd.cpp
- Client/WarFare/UIMessageWnd.h
- chat and info minimizeable
- chat and info no longer linked together (position of info stored into reg, just like the other windows)
> chat and info minimize + seperated position

- Client/WarFare/IMouseWheelInputDlg.h
- Client/WarFare/LocalInput.cpp
- Client/WarFare/UISkillTreeDlg.h
- Client/WarFare/UITransactionDlg.h
- Client/WarFare/UIWareHouseDlg.h
- Client/WarFare/WarFare.vcxproj
- Client/WarFare/WarFare.vcxproj.filters
I m new on using Git and SourceTree. I was miss to add a file and changing on configuration files to my previos branch and i was allready created pull request for it. This request is completion of request #106 
I may have mixed things together :D This request just has additional updates commit (2d4b542) for f41ce82 commit.
> For Issue #40#41#42 - PullRequest#106 Completion

- Client/WarFare/GameProcCharacterCreate.cpp
- Client/WarFare/GameProcCharacterCreate.h
- Client/WarFare/UICharacterCreate.cpp
- Client/WarFare/UICharacterCreate.h
> KO-122 fixed stats generation when creating characters

- Client/WarFare/UIChat.cpp
> KO-124 fixed knights chat button name

- Client/Option/OptionDlg.cpp
In order to make testing simpler and beginner friendly added new screen resolutions. Now can support wide variety of screen sizes. However, to take full advantage of this addition some UI components shall be readdressed like Login, Server select, chat etc.
> New screen resolutions

- Server/GameServer/GameDefine.h
- Server/GameServer/LuaEngine.cpp
- Server/GameServer/User.cpp
- Server/GameServer/User.h
- Server/GameServer/lua_bindings.cpp
- Server/GameServer/lua_bindings.h
- Server/bin/Debug/QUESTS/1.lua
- Server/bin/Debug/QUESTS/2.lua
- Server/bin/Debug/QUESTS/21.lua
- Server/bin/Release/QUESTS/1.lua
- Server/bin/Release/QUESTS/2.lua
- Server/bin/Release/QUESTS/21.lua
fix to "class change" 's packet sender is not triggered by lua. 
Now it opens, stat and skill resets also works.
> lua functions for SendStatSkillDistribute, packet sender

- Client/WarFare/UILogin_1298.cpp
color is set as yellow
color is green
original behavior
> changed to original color

- .github/workflows/codeql.yml
- Client/N3Base/N3BaseFileAccess.cpp
- Client/N3Base/N3FXGroup.cpp
- Client/N3Base/N3FXPartBase.cpp
- Client/N3Base/N3FXPartMesh.cpp
- Client/N3Base/N3FXPartParticles.cpp
- Client/N3Base/N3TerrainManager.cpp
- Client/WarFare/GameProcMain.cpp
- Client/WarFare/GameProcedure.cpp
- Client/WarFare/GrassMng.cpp
- Server/AIServer/ServerDlg.cpp
- Server/VersionManager/DBProcess.cpp
- TblEditor/TblEditorBase.cpp
- deps/ZipArchive/ZipArchive.cpp
- deps/ZipArchive/ZipStorage.cpp
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/33
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/32
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/31
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/30
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/29
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/8
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/7
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/38
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/37
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/36
Fixes https://github.com/Open-KO/KnightOnline/security/code-scanning/35
Fixes …
> Fix CodeQL alerts

- Client/N3Base/N3Base.vcxproj
- Client/N3Base/N3Base.vcxproj.filters
- Client/N3Base/N3GlobalEffectMng.cpp
- Client/N3Base/N3GlobalEffectMng.h
This is still used by SkyViewer.
> Restore CN3GlobalEffectMng

- .github/workflows/build_client.yml
- .github/workflows/build_client_tools.yml
- .github/workflows/build_server.yml
- .github/workflows/build_tools.yml
This got dropped, but it should ideally stay.
> Fix workflows not filtering push events to master

- Client/N3Base/N3UIBase.cpp
> CN3UIBase::Load(): Formatting and minor cleanup pass

- Client/WarFare/UIQuestMenu.cpp
- Client/WarFare/UIQuestMenu.h
- Client/WarFare/UIQuestTalk.cpp
- Client/WarFare/UIQuestTalk.h
Scroll does not work for UIQuestTalk, and UIQuestMenu
Scroll added and working properly.
Seperate SetTopLine functions added for both classes to set top line with scroll input.
> CUIQuestMenu, CUIQuestTalk: Add scrollbar support

- Client/WarFare/UIManager.cpp
- Client/WarFare/UIManager.h
Also fix a bug causing them to only be appended to; we clear them after use now
Resolves #391 (which is random related breakage due to too much being allocated)
> Speed up debug string rendering

- Client/WarFare/MagicSkillMng.cpp
NULL macro exists
replaced with nullptr
code cleanup
> MagicSkillMng.cpp: NULL -> nullptr

- Client/WarFare/UIDead.cpp
- Client/WarFare/UIDead.h
code cleanup, NULL macro to nullptr, spacing, N3_VERIFY_UI_COMPONENT instead __ASSERT
> CUIDead: Reformatter pass + minor code cleanup

- Client/WarFare/UIDroppedItemDlg.cpp
- Client/WarFare/UIDroppedItemDlg.h
NULL to nullptr, log in debug only, spacing, N3_VERIFY_UI_COMPONENT
> CUIDroppedItemDlg: Reformatter pass and cleanup

- Client/WarFare/UIWareHouseDlg.cpp
- Client/WarFare/UIWareHouseDlg.h
> CUIWareHouseDlg: Reformatter pass and minor code cleanup

- Client/WarFare/GameProcMain.cpp
- Client/WarFare/GameProcMain.h
- Client/WarFare/PacketDef.h
- Server/Ebenezer/User.cpp
- Server/shared/globals.h
- Server/shared/packets.h
gold gain overflows
sum as int64_t , overflow check with INT_MAX, check negative gold
This bug can be result in negative gold.
> CUser::GoldGain(): Fix overflow

- Client/WarFare/UICmdList.cpp
- Client/WarFare/UICmdList.h
Mousewheel has no effect on selected items.
List can be navigated with mousewheel.
This is a behavior which exists in official client.
> CUICmdList: Implement OnMouseWheelEvent

- Client/WarFare/GameDef.h
- Client/WarFare/GameProcMain.cpp
- Client/WarFare/PlayerMySelf.cpp
target to pTarget - hungarian notation
removed: assignment target = nullptr on fail
removed: recheck inside if block for camera
replaced: MD_FOWARD as MD_FORWARD
replaced: -1 magic number with SKILLMAGIC_TARGET_UNKNOWN Sentinel
> Clean up GameProcMain::TryAttack()

- Client/WarFare/GameProcMain.cpp
- Client/WarFare/N3UIIcon.cpp
- Client/WarFare/N3UIWndBase.cpp
- Client/WarFare/N3UIWndBase.h
- Client/WarFare/SubProcPerTrade.cpp
- Client/WarFare/UIDroppedItemDlg.cpp
- Client/WarFare/UIHotKeyDlg.cpp
- Client/WarFare/UIInventory.cpp
- Client/WarFare/UIItemExchange.cpp
- Client/WarFare/UIManager.cpp
- Client/WarFare/UIPerTradeDlg.cpp
- Client/WarFare/UISkillTreeDlg.cpp
- Client/WarFare/UITransactionDlg.cpp
- Client/WarFare/UIWareHouseDlg.cpp
They're currently named m\_\* even though they're static. They should be s\_\*.
> Rename CN3UIWndBase's static vars to indicate they're static

- Server/Ebenezer/User.cpp
> CUser::ItemTrade(): Fix purchase overflow/underflow

- Server/Ebenezer/LOGIC_ELSE.cpp
- Server/Ebenezer/User.cpp
- CHECK_LV
- HOWMUCH_ITEM
- NOEXIST_COM_EVENT
- EXIST_COM_EVENT
#260
> Implement more EVT Logic

- Server/Ebenezer/LOGIC_ELSE.cpp
- Server/Ebenezer/User.cpp
- Server/Ebenezer/User.h
* Added implementation for checking the clan grade
#260
> Implement CHECK_CLAN_GRADE

- Server/AIServer/Npc.cpp
- Server/AIServer/Npc.h
- Server/AIServer/ServerDlg.cpp
- Server/AIServer/ServerDlg.h
As per official, this is enforced on the first 2 slots (indexed 1 and 3, here), for (at least in the first slot) groups 100+.
Resolves #596
> Implement drop groups (MAKE_ITEM_GROUP)
